mj:
#  api-secret: dea554f25d16765864dbddee641e8741
  discord:
    guild-id: 1146387141815959642
    channel-id: 1146387142306701344
    user-token: MTEwNzI2MzE4OTY0Njg1MjE4Ng.GsV8zF.eYKvbbjj6_peFeTCpJtreIknFOGmPwu7fpO4xo
    session-id: 720b71d87fe71093b1b87e80ed837ce7
    user-wss: true
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  task-store:
    type: in_memory
    timeout: 30d
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
  proxy:
    host: 172.20.0.1
    port: 7078